services:
  - type: web
    name: churn-app
    env: python
    plan: free
    region: oregon
    python:
      version: 3.9.18
    buildCommand: |
      pip install --upgrade pip==23.1.2 setuptools==65.5.0 wheel==0.40.0
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
