services:
  - type: web
    name: churn-app
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
    disk:
      name: data
      mountPath: /var/lib/data
      sizeGB: 1